[package]
name = "autoreturn-pool"
authors = ["Sild <silddev@proton.me>"]
repository = "https://github.com/Sild/autoreturn-pool"
description = "A simple pool that returns items automatically after it's dropped"
version = "0.1.2"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
log = "0.4.22"

[dev-dependencies]
anyhow = "1.0.87"
