[package]
name = "async-autoreturn-pool"
authors = ["Sild <sildtm@icloud.com>"]
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1.40.0", features = ["sync"]}
anyhow = "1.0.87"