name: Publish

on:
  workflow_dispatch:
    inputs:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_IO_REGISTRY_TOKEN }}
          args: -p async-autoreturn-pool --no-verify
